server:
  port: 4840
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace